import "./globals.css";
import { Inter } from "next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header
          style={{
            display: "flex",
            justifyContent: "space-around",
            alignItems: "center",
            width: "80%",
            margin: "0px auto 30px",
            padding: "10px",
            color: "red",
            fontSize: "25px",
            fontWeight: "bolder",
            textTransform: "capitalize",
            backgroundColor: "black",
            color: "white",
          }}
        >
          <Link style={{ textDecoration: "none" }} href="/posts">
            posts
          </Link>
          <Link style={{ textDecoration: "none" }} href="/articles">
            articles
          </Link>
        </header>

        {children}
      </body>
    </html>
  );
}
